// <auto-generated />
namespace AngularJSAuthentication.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class w2p : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(w2p));
        
        string IMigrationMetadata.Id
        {
            get { return "201512160846520_w2p"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
